name: Build and test

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0

jobs:
  build:
    name: Build
    strategy:
      matrix:
        toolchain:
          - name: msrv
            version: 1.88
          - name: stable
            version: stable
        os:
          - name: linux
            version: ubuntu-latest
          - name: windows
            version: windows-latest
          - name: macos
            version: macos-latest
    runs-on: ${{ matrix.os.version }}

    steps:
      - uses: actions/checkout@v6

      - name: Cache Rust
        uses: actions/cache@v5
        with:
          path: ~/.rustup
          key: rustup-${{ matrix.os.version }}-${{ matrix.toolchain.version }}
      - name: Cache Cargo
        uses: actions/cache@v5
        with:
          path: ~/.cargo
          key: cargo-${{ matrix.os.version }}-${{ matrix.toolchain.version }}

      # Install Linux system dependencies required for Dioxus
      - name: Install Linux dependencies
        if: matrix.os.name == 'linux'
        env:
          DEBIAN_FRONTEND: noninteractive
          APT_LISTCHANGES_FRONTEND: none
        run: |
          sudo apt-get update -y
          sudo apt-get remove -y needrestart || true
          sudo apt-get install -y libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev libxdo-dev patchelf

      # Install toolchain
      - name: Install Rust toolchain
        run: rustup toolchain install ${{ matrix.toolchain.version }}
      - name: Set default toolchain
        run: rustup default ${{ matrix.toolchain.version }}
      - name: Install clippy
        if: matrix.toolchain.name == 'stable'
        run: rustup component add clippy
      - name: Install dioxus-cli
        run: cargo install dioxus-cli

      # Build
      - name: Build (Linux)
        if: matrix.os.name == 'linux'
        run: |
          ./desktop-build-linux.sh
          sudo ./desktop-install-linux.sh
      - name: Build (Windows)
        if: matrix.os.name == 'windows'
        run: desktop-build-windows.cmd
        shell: cmd
      - name: Build (MacOS)
        if: matrix.os.name == 'macos'
        run: ./desktop-build-macos.sh

      # Clippy
      - name: Clippy
        if: matrix.toolchain.name == 'stable'
        run: cargo clippy -- -D warnings

# vim: ts=2 sw=2 expandtab
